import Button from 'components/common/Button';
import type { NextPage } from 'next';
import Head from 'next/head';
import { useRecoilState } from 'recoil';
import { counterState } from 'store/atom';

const Home: NextPage = () => {
  const [counter, setCounter] = useRecoilState(counterState);

  const handleClick = () => {
    setCounter(counter + 1);
  };

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-col items-center space-y-2">
        <h1 className=" font-medium text-xl">Hello World</h1>
        <p>Count: {counter}</p>
        <Button
          className="bg-black text-white p-2 rounded-md"
          onClick={handleClick}
        >
          Increase
        </Button>
      </main>
    </div>
  );
};

export default Home;
