import type { GetServerSideProps, NextPage } from 'next';
import Head from 'next/head';
import { useRecoilState } from 'recoil';
import { dehydrate, QueryClient, useQuery, UseQueryResult } from 'react-query';
import { counterState } from 'store/atom';
import Button from 'components/common/Button';
import { getTodos } from 'api/sample';
import { SampleResponse } from 'types/sample';

const Home: NextPage = () => {
  const { data: todos }: UseQueryResult<SampleResponse> = useQuery(
    'todos',
    getTodos,
  );
  const [counter, setCounter] = useRecoilState(counterState);

  const handleClick = () => {
    setCounter(counter + 1);
  };

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-col items-center space-y-2">
        <h1 className=" font-medium text-xl">Hello World</h1>
        <p>Count: {counter}</p>
        <Button
          className="bg-black text-white p-2 rounded-md"
          onClick={handleClick}
        >
          Increase
        </Button>
        <div>
          <h2>Todos</h2>
          <ul>
            {todos?.data?.map((todo, idx) => (
              <li key={idx}>{todo?.title}</li>
            ))}
          </ul>
        </div>
      </main>
    </div>
  );
};

export const getServerSideProps: GetServerSideProps = async () => {
  const queryClient = new QueryClient();
  await queryClient.prefetchQuery('todos', getTodos);

  return {
    props: {
      dehydratedState: dehydrate(queryClient),
    },
  };
};

export default Home;
