import type { GetServerSideProps } from 'next';
import Head from 'next/head';
import { ReactElement } from 'react';

import { useRecoilState } from 'recoil';
import { dehydrate, QueryClient, useQuery, UseQueryResult } from 'react-query';
import { SubmitHandler, useForm } from 'react-hook-form';
import { counterState } from 'store/atom';
import Button from 'components/common/Button';
import Input from 'components/common/Input';
import { getTodo } from 'api/sample';
import { SampleResponse } from 'types/sample';
import TextArea from 'components/common/TextArea';
import Layout from 'components/layout';

type FormValues = {
  name: string;
  textarea: string;
};

const Home = () => {
  const { data: todo }: UseQueryResult<SampleResponse> = useQuery(
    'todos',
    getTodo,
  );
  const [counter, setCounter] = useRecoilState(counterState);
  const { register, handleSubmit } = useForm<FormValues>({
    mode: 'onChange',
  });

  const handleClick = () => {
    setCounter(counter + 1);
  };

  const onValid: SubmitHandler<FormValues> = (data) => {
    console.log(data);
  };

  return (
    <div>
      <Head>
        <title>Page Title</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-col items-center space-y-2">
        <h1 className=" font-medium text-xl">Boilerplate</h1>
        <p>Todo: {todo?.data.title}</p>
        <p>Count: {counter}</p>
        <Button
          className="bg-black text-white p-2 rounded-md"
          onClick={handleClick}
        >
          Increase
        </Button>

        <form
          className="flex flex-col space-y-5 pt-5"
          onSubmit={handleSubmit(onValid)}
        >
          <Input
            className="border-sky-200 ring-1 p-2"
            type="text"
            name="name"
            register={register('name')}
            placeholder="Input Something"
          />
          <TextArea
            className="border-sky-200 ring-1 p-2"
            name="textarea"
            register={register('textarea')}
            placeholder="Input Something"
          />
        </form>
      </main>
    </div>
  );
};

Home.getLayout = function getLayout(page: ReactElement) {
  return <Layout>{page}</Layout>;
};

export const getServerSideProps: GetServerSideProps = async () => {
  const queryClient = new QueryClient();
  await queryClient.prefetchQuery('todo', getTodo);

  return {
    props: {
      dehydratedState: dehydrate(queryClient),
    },
  };
};

export default Home;
